import {
  BookOpen, Users, Heart, Leaf, Cpu, Lightbulb, Globe2, Vote, Wallet, 
  TrendingUp, Activity, MapPin, Calendar, MessageSquare, User, 
  Zap, Bitcoin, Settings2, RefreshCw, AlertTriangle, Mail, Bell, BellOff,
  Search, Filter, ArrowUpCircle, ArrowDownCircle, CheckCircle2,
  XCircle, Clock, BarChart3, PieChart, TrendingDown, Send,
  Download, Upload, Eye, EyeOff, Lock, Unlock, Shield, Key,
  Trash2, Edit, Edit2, Plus, Minus, X, Check, ChevronDown, ChevronUp,
  ChevronLeft, ChevronRight, ExternalLink, Copy, Share2, Star,
  Flag, Tag, Bookmark, FileText, Image, Video, Music, File,
  Folder, Home, Menu, MoreVertical, MoreHorizontal, Info,
  HelpCircle, AlertCircle, AlertOctagon, CheckCircle, XOctagon,
  Loader, Loader2, RotateCw, Save, ArrowLeft, ArrowRight,
  ArrowUp, ArrowDown, LogOut, LogIn, UserPlus, UserMinus, UserCheck,
  UserX, Users2, Link2, Unlink, Code, Terminal, Github, GitBranch,
  GitCommit, GitMerge, GitPullRequest, Package, Database, Server,
  Cloud, CloudOff, Wifi, WifiOff, Bluetooth, Cast, Radio, Tv,
  Smartphone, Tablet, Laptop, Monitor, Printer, Keyboard, Mouse,
  Speaker, Volume, Volume1, Volume2, VolumeX, Mic, MicOff, Camera,
  CameraOff, Power, Battery, BatteryCharging, BatteryLow, Plug,
  ThumbsUp, ThumbsDown, Smile, Frown, Meh, Laugh, Angry, Flame,
  Award, Trophy, Medal, Target, Crosshair, Compass, Map, Navigation,
  Anchor, Plane, Car, Bike, Bus, Train, Ship, Rocket, Sun, Moon,
  CloudRain, CloudSnow, Wind, Droplets, Thermometer, Umbrella,
  Coffee, Pizza, Beer, Cake, IceCream, Cookie, Apple, Banana,
  Cherry, Grape,
  Briefcase, Building, Building2, Store, Factory, Warehouse, School,
  Hospital, Hotel, Church, Landmark, Castle, TreePine, Mountain,
  Waves, Tent, Bed, Bath, DoorOpen, DoorClosed, PaintBucket,
  Hammer, Wrench, Cog, Settings, Sliders, ToggleLeft,
  ToggleRight, Power as PowerIcon, PlayCircle, PauseCircle, StopCircle,
  SkipBack, SkipForward, Rewind, FastForward, Repeat, Repeat1, Shuffle,
  List, Grid, Columns, Rows, Layout, Sidebar, PanelLeft, PanelRight,
  Maximize, Minimize, Expand, Shrink, ZoomIn, ZoomOut, Move, Crop,
  Layers, Package2, Box, Archive, Inbox, Send as SendIcon, MailOpen,
  MailPlus, MailMinus, MailCheck, MailX, MailSearch, MailQuestion,
  PhoneCall, PhoneIncoming, PhoneOutgoing, PhoneMissed, PhoneOff,
  MessageCircle, MessagesSquare, MessageSquarePlus,
  AlarmClock, Timer, Hourglass, Watch, CalendarDays, CalendarCheck,
  CalendarClock, CalendarX, CalendarPlus, CalendarMinus, CalendarRange,
  Paperclip, AtSign, Hash, DollarSign, Euro, Percent, Equal,
  PlusCircle, MinusCircle, Divide, Asterisk, Binary,
  CircleDot, Circle, Square, Triangle, Pentagon, Hexagon, Octagon,
  Diamond, Heart as HeartIcon, Spade, Club, ArrowRightLeft, Sigma, Infinity, Pi,
  DatabaseZap, CircleGauge, ChartNoAxesGantt, Palette, Handshake, HeartOff,
  Phone, StarOff, Link, ArrowUpRight, Sparkles, QrCode, Globe,
  Ban, BrainCircuit, HeartPulse, History, RotateCcw, Reply, Scale, Network,
  Gauge, UserCircle, Cuboid
} from 'lucide-react';

export const iconMap = {
  BookOpen, Users, Heart, Leaf, Cpu, Lightbulb, Globe2, Vote, Wallet,
  TrendingUp, Activity, MapPin, Calendar, MessageSquare, User,
  Zap, Bitcoin, Settings2, RefreshCw, AlertTriangle, Mail, Bell, BellOff,
  Search, Filter, ArrowUpCircle, ArrowDownCircle, CheckCircle2,
  XCircle, Clock, BarChart3, PieChart, TrendingDown, Send,
  Download, Upload, Eye, EyeOff, Lock, Unlock, Shield, Key,
  Trash2, Edit, Edit2, Plus, Minus, X, Check, ChevronDown, ChevronUp,
  ChevronLeft, ChevronRight, ExternalLink, Copy, Share2, Star,
  Flag, Tag, Bookmark, FileText, Image, Video, Music, File,
  Folder, Home, Menu, MoreVertical, MoreHorizontal, Info,
  HelpCircle, AlertCircle, AlertOctagon, CheckCircle, XOctagon,
  Loader, Loader2, RotateCw, Save, ArrowLeft, ArrowRight,
  ArrowUp, ArrowDown, LogOut, LogIn, UserPlus, UserMinus, UserCheck,
  UserX, Users2, Link2, Unlink, Code, Terminal, Github, GitBranch,
  GitCommit, GitMerge, GitPullRequest, Package, Database, Server,
  Cloud, CloudOff, Wifi, WifiOff, Bluetooth, Cast, Radio, Tv,
  Smartphone, Tablet, Laptop, Monitor, Printer, Keyboard, Mouse,
  Speaker, Volume, Volume1, Volume2, VolumeX, Mic, MicOff, Camera,
  CameraOff, Power, Battery, BatteryCharging, BatteryLow, Plug,
  ThumbsUp, ThumbsDown, Smile, Frown, Meh, Laugh, Angry, Flame,
  Award, Trophy, Medal, Target, Crosshair, Compass, Map, Navigation,
  Anchor, Plane, Car, Bike, Bus, Train, Ship, Rocket, Sun, Moon,
  CloudRain, CloudSnow, Wind, Droplets, Thermometer, Umbrella,
  Coffee, Pizza, Beer, Cake, IceCream, Cookie, Apple, Banana,
  Cherry, Grape,
  Briefcase, Building, Building2, Store, Factory, Warehouse, School,
  Hospital, Hotel, Church, Landmark, Castle, TreePine, Mountain,
  Waves, Tent, Bed, Bath, DoorOpen, DoorClosed, PaintBucket,
  Hammer, Wrench, Cog, Settings, Sliders, ToggleLeft,
  ToggleRight, PowerIcon, PlayCircle, PauseCircle, StopCircle,
  SkipBack, SkipForward, Rewind, FastForward, Repeat, Repeat1, Shuffle,
  List, Grid, Columns, Rows, Layout, Sidebar, PanelLeft, PanelRight,
  Maximize, Minimize, Expand, Shrink, ZoomIn, ZoomOut, Move, Crop,
  Layers, Package2, Box, Archive, Inbox, SendIcon, MailOpen,
  MailPlus, MailMinus, MailCheck, MailX, MailSearch, MailQuestion,
  PhoneCall, PhoneIncoming, PhoneOutgoing, PhoneMissed, PhoneOff,
  MessageCircle, MessagesSquare, MessageSquarePlus,
  AlarmClock, Timer, Hourglass, Watch, CalendarDays, CalendarCheck,
  CalendarClock, CalendarX, CalendarPlus, CalendarMinus, CalendarRange,
  Paperclip, AtSign, Hash, DollarSign, Euro, Percent, Equal,
  PlusCircle, MinusCircle, Divide, Asterisk, Binary,
  CircleDot, Circle, Square, Triangle, Pentagon, Hexagon, Octagon,
  Diamond, HeartIcon, Spade, Club, ArrowRightLeft, Sigma, Infinity, Pi,
  DatabaseZap, CircleGauge, ChartNoAxesGantt, Palette, Handshake, HeartOff,
  Phone, StarOff, Link, ArrowUpRight, Sparkles, QrCode, Globe,
  Ban, BrainCircuit, HeartPulse, History, RotateCcw, Reply, Scale, Network,
  Gauge, UserCircle, Cuboid,
  // Alias für "Document" -> verweist auf FileText
  Document: FileText
};